# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"l\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\x05token\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rerror_message\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_tokenB\x10\n\x0e_error_message\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05story\x18\x01 \x01(\t\"Q\n\rEmbedResponse\x12\x12\n\nembeddings\x18\x01 \x03(\x02\x12\x1a\n\rerror_message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_error_messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=17
  _globals['_LOGINREQUEST']._serialized_end=67
  _globals['_LOGINRESPONSE']._serialized_start=69
  _globals['_LOGINRESPONSE']._serialized_end=177
  _globals['_EMBEDREQUEST']._serialized_start=179
  _globals['_EMBEDREQUEST']._serialized_end=208
  _globals['_EMBEDRESPONSE']._serialized_start=210
  _globals['_EMBEDRESPONSE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
